Repository Swarnimashukla/Automatic-attendance-management-system, pull requests merged in 2021-04, with the labels that each got.

#134 Added auto label for issues
  .github/workflows/issue.yml
Labels: Level0, gssoc21

#155 RollCall_footer
  Rollcall_Footer/index.html
  Rollcall_Footer/style.css
Labels: Level1, gssoc21

#153 Issue 138
  SETUP.md
  __pycache__/get_status.cpython-37.pyc
  __pycache__/global_variables.cpython-37.pyc
Labels: Level1, gssoc21

#154 Issues 119-Added the UI Design of landing page
  Design/Rollcall-landing-page.png
Labels: Level3, gssoc21

#151 Update Issue template
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: Level0, gssoc21

#157 Classification of images(male and female) using CNN
  Image-Classification/.idea/.gitignore
  Image-Classification/.idea/.name
  Image-Classification/.idea/Image-Classification.iml
  Image-Classification/.idea/inspectionProfiles/profiles_settings.xml
  Image-Classification/.idea/misc.xml
  Image-Classification/.idea/modules.xml
  Image-Classification/.idea/vcs.xml
  Image-Classification/.vscode/settings.json
  Image-Classification/Dataset-Link.txt
  Image-Classification/Image-Classification.py
  Image-Classification/network_json
  Image-Classification/weights.hdf5
Labels: Level2, gssoc21

#164 Added contributors at bottom of readme file
  README.md
Labels: Level0, gssoc21

#165 Added the no.of forks, issues, pr's and license and repo size
  README.md
Labels: Level0, gssoc21
