Repository Swarnimashukla/Automatic-attendance-management-system, pull requests merged in 2021-03, with the labels that each got.

#42 added pr template
  .github/pull_request_template.md
Labels: Level0, gssoc21

#60 added images in a single folder
  Capture.JPG
  README.md
  Resource/AAMS.jpg
  Resource/Rollcall.png
  Resource/Winner.jpeg
  Resource/o.PNG
  Resource/r.PNG
  Resource/use case.PNG
  Rollcall.PNG
Labels: Level0, gssoc21

#72 Created requirement.txt
  requirements.txt
Labels: Level0, gssoc21

#97 Logo Files
  Resource/Logo_Design1 _Garvitraj_Pandey.png
  Resource/Logo_Design2 _Garvitraj_Pandey.png
  Resource/Logo_Design3 _Garvitraj_Pandey.png
Labels: Level0, gssoc21

#98 Update README.md
  README.md
Labels: Level0, gssoc21

#93 logo added
  Resource/Logo_Design _Sapna2001_Blue.png
  Resource/Logo_Design _Sapna2001_WithoutBackground.png
Labels: Level0, gssoc21

#99 Adding Features Page Wireframe
  Resource/Features Page Wireframe (1).png
  Resource/Features Page Wireframe (2).png
Labels: Level2, gssoc21

#102 added logo for RollCall
  Resource/RollCall.JPG
  Resource/RollCall.PNG
  Resource/RollCall.svg
  Resource/Roll_call_favicon_io/android-chrome-192x192.png
  Resource/Roll_call_favicon_io/android-chrome-512x512.png
  Resource/Roll_call_favicon_io/apple-touch-icon.png
  Resource/Roll_call_favicon_io/favicon-16x16.png
  Resource/Roll_call_favicon_io/favicon-32x32.png
  Resource/Roll_call_favicon_io/favicon.ico
  Resource/Roll_call_favicon_io/site.webmanifest
Labels: Level0, gssoc21

#104 Adding Landing Page Wireframe
  Resource/Landing Page Wireframe (1).png
  Resource/Landing Page Wireframe (2).png
  Resource/Landing Page Wireframe (3).png
  Resource/Landing Page Wireframe (4).png
  Resource/Landing Page Wireframe (5).png
Labels: Level2, gssoc21

#105 Modified Logo Design
  Resource/Logo_Design_Deepthi.PNG
Labels: Level0, gssoc21

#106 Add issue templates
  .github/workflows/ISSUE_TEMPLATE/documentation.md
  .github/workflows/ISSUE_TEMPLATE/feature.md
  .github/workflows/ISSUE_TEMPLATE/proposal.md
  CONTRIBUTING.md
Labels: Level1, gssoc21

#113 Updated README.md
  README.md
Labels: Beginner-friendly, Level0, gssoc21

#112 Added code of conduct
  CODE_OF_CONDUCT.md
Labels: Level0, gssoc21

#131 UI for Features Page
  Resource/FeaturePage_UI_Deepthi.png
Labels: Level3, gssoc21

#130 Face_EyeDetection
  Face_EyeDetection/face_detects.py
  Face_EyeDetection/haarcascade_eye.xml
  Face_EyeDetection/haarcascade_frontalface_default.xml
Labels: Level2, gssoc21

#136 IA for ROLLCALL
  Resource/IA_Asmita Si.jpg
Labels: Level1, gssoc21
